### PR TITLE
Update dependencies

### LINKED ISSUE #67: Moving to jira-ruby 1.6.0?
Hi there! What do you think about moving to jira-ruby-1.6.0 (just to not stick on the old deps releases :D)?

### PR DESCRIPTION
**Pull request by ghosteathuman**
Update Gem dependencies.

Resolves #67

### CODE REVIEW

**Comment by ghosteathuman** [comment]
@keepcosmos I am wondering if you are able to review this PR?

**Comment by keepcosmos** [comment]
@ghosteathuman Sorry I'm late. I will check in a week

**Comment by keepcosmos** [comment]
I haven't use Jira recently. so It's difficult to maintain.
Can you be a maintainer for Terjira?

**Comment by ghosteathuman** [comment]
@keepcosmos I would be delighted if you would add me as a maintainer.

**Comment by keepcosmos** [comment]
I sent invite mail to you. Could you give me a mail for knowing your mail address.

**Comment by msva** [comment]
@keepcosmos @ghosteathuman can you also work on giving maintenance access to the terjira gem on rubygems to @ghosteathuman , so he can also push new version with bumped deps? :)

**Pull request merged**
